05:47:33 PM: DEBUG [logger_base.py:19] Mensaje a nivel debug
05:47:33 PM: INFO [logger_base.py:20] Mensaje a nivel de info
05:47:33 PM: WARNING [logger_base.py:21] Mensaje a nivel de warning
05:47:33 PM: ERROR [logger_base.py:22] Mensaje a nivel de error
05:47:33 PM: CRITICAL [logger_base.py:23] Mensaje a nivel critical
05:59:19 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:01:40 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:04:50 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:04:50 PM: DEBUG [persona.py:56] 
            Id Persona: None, Nombre: Juan
            Apellido: Perez, Email: jperez@email.com 
        
06:06:26 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:06:26 PM: DEBUG [persona.py:56] 
            Id Persona: None, Nombre: Juan
            Apellido: Perez, Email: jperez@email.com 
        
06:06:26 PM: DEBUG [persona.py:60] 
            Id Persona: 1, Nombre: None
            Apellido: None, Email: None 
        
07:48:09 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x74431254fec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
07:50:29 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x726fa4e1bec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
07:50:29 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x726fa4cc25c0; closed: 0>
08:11:25 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7a6bff2fbec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:11:25 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x7a6bff3d26b0; closed: 0>
08:11:25 PM: DEBUG [persona_dao.py:32] 
            Id Persona: 8, Nombre: Juan Perez
            Apellido: Suarez, Email: jperez@email.com 
        
08:11:25 PM: DEBUG [persona_dao.py:32] 
            Id Persona: 9, Nombre: Angel
            Apellido: Quintana, Email: aq@email.com 
        
08:11:25 PM: DEBUG [persona_dao.py:32] 
            Id Persona: 11, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
08:11:25 PM: DEBUG [persona_dao.py:32] 
            Id Persona: 12, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
08:11:25 PM: DEBUG [persona_dao.py:32] 
            Id Persona: 13, Nombre: Carlos
            Apellido: Lara, Email: Clara@mail.com 
        
08:11:25 PM: DEBUG [persona_dao.py:32] 
            Id Persona: 14, Nombre: Alex
            Apellido: Rojas, Email: Arojas@mail.com 
        
08:29:10 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x79b2d5383ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:30:55 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x76de69d9bec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:33:55 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7d827fb83ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:36:52 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x71b64cf5fec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:38:37 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x77d388a13ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:38:37 PM: DEBUG [persona_dao.py:33] Persona a insertar: 
            Id Persona: None, Nombre: Pedro
            Apellido: Perez, Email: pp@email.com 
        
08:38:37 PM: DEBUG [persona_dao.py:37] Persona insertada correctamente: 
            Id Persona: None, Nombre: Pedro
            Apellido: Perez, Email: pp@email.com 
        
08:38:37 PM: DEBUG [persona_dao.py:45] Personas insertadas: 1
08:38:37 PM: ERROR [conexion.py:39] Ocurrio una exepcion al obtener el cursor: type object 'Conexion' has no attribute 'obtener_conexion'
08:40:04 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7e76abea3ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:40:04 PM: DEBUG [persona_dao.py:33] Persona a insertar: 
            Id Persona: None, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
08:40:04 PM: DEBUG [persona_dao.py:37] Persona insertada correctamente: 
            Id Persona: None, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
08:40:04 PM: DEBUG [persona_dao.py:45] Personas insertadas: 1
08:40:04 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x7e76abf7a890; closed: 0>
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 8, Nombre: Juan Perez
            Apellido: Suarez, Email: jperez@email.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 9, Nombre: Angel
            Apellido: Quintana, Email: aq@email.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 11, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 12, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 13, Nombre: Carlos
            Apellido: Lara, Email: Clara@mail.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 14, Nombre: Alex
            Apellido: Rojas, Email: Arojas@mail.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 15, Nombre: Pedro
            Apellido: Perez, Email: pp@email.com 
        
08:40:04 PM: DEBUG [persona_dao.py:50] 
            Id Persona: 16, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
08:46:21 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7930edb5fec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:46:21 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x7930eda065c0; closed: 0>
08:46:21 PM: DEBUG [persona_dao.py:33] Persona a insertar: 
            Id Persona: None, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
08:46:21 PM: DEBUG [persona_dao.py:36] Persona insertada correctamente: 
            Id Persona: None, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
08:46:21 PM: DEBUG [persona_dao.py:44] Personas insertadas: 1
08:59:48 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7804e9d03ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
09:00:16 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7fd72e2c3ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
09:00:26 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x78efd4103ec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
09:00:26 PM: DEBUG [persona_dao.py:46] Persona actualizada: 
            Id Persona: 16, Nombre: Jorge
            Apellido: Eliecer, Email: Je@email.com 
        
09:00:26 PM: DEBUG [persona_dao.py:58] Personas actualizadas: 1
09:00:26 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x78efd3faa5c0; closed: 0>
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 8, Nombre: Juan Perez
            Apellido: Suarez, Email: jperez@email.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 9, Nombre: Angel
            Apellido: Quintana, Email: aq@email.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 11, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 12, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 13, Nombre: Carlos
            Apellido: Lara, Email: Clara@mail.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 14, Nombre: Alex
            Apellido: Rojas, Email: Arojas@mail.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 15, Nombre: Pedro
            Apellido: Perez, Email: pp@email.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 16, Nombre: Jorge
            Apellido: Eliecer, Email: Je@email.com 
        
09:00:26 PM: DEBUG [persona_dao.py:63] 
            Id Persona: 17, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
09:08:27 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x7dadded84680; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
09:08:27 PM: DEBUG [persona_dao.py:55] Objeto eliminado: 
            Id Persona: 12, Nombre: None
            Apellido: None, Email: None 
        
09:08:27 PM: DEBUG [persona_dao.py:72] Personas eliminadas 1
09:08:27 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x7daddf74a5c0; closed: 0>
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 8, Nombre: Juan Perez
            Apellido: Suarez, Email: jperez@email.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 9, Nombre: Angel
            Apellido: Quintana, Email: aq@email.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 11, Nombre: Maria
            Apellido: Esparza, Email: Mesparza@mail.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 13, Nombre: Carlos
            Apellido: Lara, Email: Clara@mail.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 14, Nombre: Alex
            Apellido: Rojas, Email: Arojas@mail.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 15, Nombre: Pedro
            Apellido: Perez, Email: pp@email.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 16, Nombre: Jorge
            Apellido: Eliecer, Email: Je@email.com 
        
09:08:27 PM: DEBUG [persona_dao.py:77] 
            Id Persona: 17, Nombre: Jorge
            Apellido: Vega, Email: jv@email.com 
        
11:09:23 AM: INFO [conexion.py:25] Creacion del pool exitosa <psycopg2.pool.SimpleConnectionPool object at 0x70041d516e50>
11:09:23 AM: INFO [conexion.py:35] Conexion obtenida del pool <connection object at 0x70041c775080; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
11:09:23 AM: INFO [conexion.py:35] Conexion obtenida del pool <connection object at 0x70041c3f4040; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
